spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ccwme
    password: cwm1134128812
    url: jdbc:mysql://localhost:3306/employees
  web:
    resources:
      static-locations: file:F:\project\webstorm\employeemanager\build\,file:F:\project\webstorm\employeemanagerlogin\build\,file:F:\project\IDEAjavaProject\employeesmanager_filepath\
filespath: F:\project\IDEAjavaProject\employeesmanager_filepath\